### ISSUE TITLE
AttributeError: 'HaystackResultsAdmin' object has no attribute 'get_list_display'

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#10]
Follow on from https://github.com/tolomea/django-data-browser/issues/5 , slightly different

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 130, in query_html
    config = _get_config(request)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 75, in _get_config
    orm_models = get_models(request)
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 300, in get_models
    model_admins, admin_fields = _get_all_admin_fields(request)
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 121, in _get_all_admin_fields
    all_admin_fields[model].update(model_admin.get_list_display(request))
AttributeError: 'HaystackResultsAdmin' object has no attribute 'get_list_display'
```

**Comment by jayvdb** [comment]
Also

```py
Traceback (most recent call last):
...
  File "data_browser/orm.py", line 132, in _get_all_admin_fields
    for inline in model_admin.get_inline_instances(request):
AttributeError: 'HaystackResultsAdmin' object has no attribute 'get_inline_instances'
```

**Comment by tolomea** [comment]
do you know of a repo somewhere that can be used to quickly reproduce this?

**Comment by jayvdb** [comment]
I worked around those two errors, and unfortunately the model appeared in the list.

And that model doesnt work.  Here is the error that I get when the model is loaded in the browser.

```py
  File ".../data_browser/orm.py", line 461, in admin_get_queryset
    return admin.get_queryset(request)
AttributeError: 'HaystackResultsAdmin' object has no attribute 'get_queryset'
```

So the fix for all of these is not to catch the errors.

IMO what should be done is that attributes `get_queryset` (and alternatives) are checked first , and the model not inspected (which causes all these errors) if it wont be usable anyway. 

This is what you concluded at https://github.com/tolomea/django-data-browser/issues/5#issuecomment-678442685

**Comment by jayvdb** [comment]
> do you know of a repo somewhere that can be used to quickly reproduce this?

https://github.com/kezabelle/django-haystackbrowser and https://github.com/django-haystack/django-haystack are really easy to set up without integrating them at all.  Empty project and just add them to INSTALLED_APPS.  Maybe a few default settings are needed.

But I think we should be focusing on `get_queryset`.

But, here is my patch to get that "working" through the inspection logic.  Let me know if you want it submitted as a PR

```diff
diff --git a/data_browser/orm.py b/data_browser/orm.py
index b327123..0f8b502 100644
--- a/data_browser/orm.py
+++ b/data_browser/orm.py
@@ -118,7 +118,10 @@ def _get_all_admin_fields(request):
         model_admins[model] = model_admin
         if visible(model_admin, request):
             all_admin_fields[model].update(from_fieldsets(model_admin, True))
-            all_admin_fields[model].update(model_admin.get_list_display(request))
+            try:
+                all_admin_fields[model].update(model_admin.get_list_display(request))
+            except AttributeError:
+                pass
             all_admin_fields[model].update(getattr(model_admin, "ddb_extra_fields", []))
             all_admin_fields[model].add(_OPEN_IN_ADMIN)
             if isinstance(model_admin, AdminMixin):
@@ -126,7 +129,11 @@ def _get_all_admin_fields(request):
             hidden_fields[model].update(getattr(model_admin, "ddb_hide_fields", []))
 
             # check the inlines, these are already filtered for access
-            for inline in model_admin.get_inline_instances(request):
+            try:
+                inlines = model_admin.get_inline_instances(request)
+            except AttributeError:
+                inlines = []
+            for inline in inlines:
                 if visible(inline, request):
                     try:
                         fk_field = _get_foreign_key(model, inline.model, inline.fk_name)
```

**Comment by tolomea** [comment]
I'm thinking about doing something like this:

```diff
diff --git a/data_browser/orm.py b/data_browser/orm.py
index b327123..69034ba 100644
--- a/data_browser/orm.py
+++ b/data_browser/orm.py
@@ -102,6 +102,12 @@ def _get_all_admin_fields(request):
                     yield f

     def visible(model_admin, request):
+        attrs = ["get_fieldsets", "model", "get_queryset"]
+        if not all(hasattr(model_admin, a) for a in attrs):
+            debug_log(
+                f"{model_admin} instance does not look like a ModelAdmin or InlineModelAdmin"
+            )
+            return False
         if getattr(model_admin, "ddb_ignore", False):
             return False
         if model_admin.has_change_permission(request):
```

That's untested, if you could verify it works that would be very helpful, otherwise when I have some time I will try setting up the haystack stuff locally.

**Comment by jayvdb** [comment]
That worked well.
I haven't checked that all previous models were still visible, but I didnt immediately spot any missing.

**Comment by tolomea** [comment]
If you have settings.DEBUG = True and a logging setup that will send
warnings to the console you should see messages for the things it's skipping

**Comment by jayvdb** [comment]
Looks good.

`partner.Partner` is from django-oscar.
`partner.Partner.location` is a custom field , it is django core gis fields.

`attachments` and `openinghours` are OSS, probably django-attachments and django-openinghours.  openinghours needs a PR patch for Django 2+ support.

```
'attachments.Attachment' has no ForeignKey to 'partner.Partner'.
<haystackbrowser.admin.HaystackResultsAdmin object at 0x7f0c2be38d60> instance does not look like a ModelAdmin or InlineModelAdmin
DDB Partner.location unsupported type PointField
DDB OpeningHours.to_hour unsupported type TimeField
DDB OpeningHours.from_hour unsupported type TimeField
```

**Comment by tolomea** [comment]
The unsupported ones fall back to str() and filtering only on is_null. I should really deal with TimeField, it's been on the todo for a bit just haven't gotten round to it.

That Attachment thing isn't coming from the data browser.

**Comment by tolomea** [comment]
> That Attachment thing isn't coming from the data browser.

That's wrong, it is, I have improved the message so it makes more sense.
