### ISSUE TITLE
Inspection causes exceptions in file storage

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#11]
If I do not have my s3 storage running, I can normally load the Django admin of models which use storage fields.

However when loading DDR, I get the following occurring, breaking the loading.

IMO it would be good to catch any errors resulting from accessing `field.storage.url` or `field.storage.path`, or really any attribute of field.storage, because lots of storage classes do not implement some attributes, often raising `NotImplementedError` or just failing badly.

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0c2a1535e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 113, in query_html
    config = _get_config(request)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 75, in _get_config
    orm_models = get_models(request)
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 307, in get_models
    models = {
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 308, in <dictcomp>
    get_model_name(model): _get_fields_for_model(
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 273, in _get_fields_for_model
    url_func=field.storage.url,
  File "/usr/lib/python3.8/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/lib/python3.8/site-packages/django/core/files/storage.py", line 364, in _setup
    self._wrapped = get_storage_class()()
  File "/usr/lib/python3.8/site-packages/minio_storage/storage.py", line 360, in __init__
    super().__init__(
  File "/usr/lib/python3.8/site-packages/minio_storage/storage.py", line 75, in __init__
    self._init_check()
  File "/usr/lib/python3.8/site-packages/minio_storage/storage.py", line 81, in _init_check
    if self.auto_create_bucket and not self.client.bucket_exists(
  File "/usr/lib/python3.8/site-packages/minio/api.py", line 453, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/lib/python3.8/site-packages/minio/api.py", line 2035, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/lib/python3.8/site-packages/minio/api.py", line 1965, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/lib/python3.8/site-packages/minio/api.py", line 1998, in _get_bucket_location
    response = self._http.urlopen(method, url,
  File "/usr/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /media?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c2a1535e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by tolomea** [comment]
This isn't too hard to deal with, although mildly annoying.
field.storage.url is a function, I don't actually call it in that code path, I'm just stashing a reference to it so I can call it later, it would appear that just touching field.storage causes django to do init stuff on the s3 storage object and that init stuff validates the bucket, hence fail.
I can move some stuff around so this is all in data formatting where I can deal with the exception.
It works in the admin because the admin just ignores exceptions in a lot of places.

**Comment by tolomea** [comment]
Thanks for these reports btw, these weird lil environment specific things can only be found by getting it into more systems, so the reports are really useful.

**Comment by tolomea** [comment]
This was difficult thing to write a test for.

**Comment by tolomea** [comment]
I'd be curious to know if this usage pattern still works on Django 4.2, my test no longer works and I'm unable to get the system into the state you describe.
