### ISSUE TITLE
django-admin-smoke-tests failures

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#13]
This is with https://github.com/greyside/django-admin-smoke-tests/pull/18 , and on Django 3.x with some extra fixes, so again hard to reproduce the scenario.  If you cant immediately see the problem and solution, leave it and I will find the fix.

```
======================================================================
ERROR: test_changelist_view (tests.test_admin_smoke.AdminSiteSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 29, in test_deco
    fn(self, model, model_admin)
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 226, in test_changelist_view
    response = model_admin.changelist_view(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 60, in changelist_view
    return super().changelist_view(request, extra_context)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/options.py", line 728, in get_changelist_instance
    return ChangeList(
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 57, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 21, in get_queryset
    fields = self.get_fields_for_request(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 14, in get_fields_for_request
    elif request.resolver_match.func.__name__ == "changelist_view":
AttributeError: 'NoneType' object has no attribute 'func'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 48, in test_deco
    six.raise_from(ModelAdminCheckException(
  File "<string>", line 3, in raise_from
django_admin_smoke_tests.tests.ModelAdminCheckException: Above exception occured while running test 'test_changelist_view' on modeladmin data_browser.ViewAdmin (View)

======================================================================
ERROR: test_changelist_view_search (tests.test_admin_smoke.AdminSiteSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 29, in test_deco
    fn(self, model, model_admin)
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 240, in test_changelist_view_search
    response = model_admin.changelist_view(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 60, in changelist_view
    return super().changelist_view(request, extra_context)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/options.py", line 728, in get_changelist_instance
    return ChangeList(
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 57, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 21, in get_queryset
    fields = self.get_fields_for_request(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 14, in get_fields_for_request
    elif request.resolver_match.func.__name__ == "changelist_view":
AttributeError: 'NoneType' object has no attribute 'func'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 48, in test_deco
    six.raise_from(ModelAdminCheckException(
  File "<string>", line 3, in raise_from
django_admin_smoke_tests.tests.ModelAdminCheckException: Above exception occured while running test 'test_changelist_view_search' on modeladmin data_browser.ViewAdmin (View)

======================================================================
ERROR: test_queryset (tests.test_admin_smoke.AdminSiteSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 29, in test_deco
    fn(self, model, model_admin)
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 207, in test_queryset
    list(model_admin.get_queryset(request))
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 21, in get_queryset
    fields = self.get_fields_for_request(request)
  File "/usr/lib/python3.8/site-packages/data_browser/helpers.py", line 14, in get_fields_for_request
    elif request.resolver_match.func.__name__ == "changelist_view":
AttributeError: 'NoneType' object has no attribute 'func'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django_admin_smoke_tests/tests.py", line 48, in test_deco
    six.raise_from(ModelAdminCheckException(
  File "<string>", line 3, in raise_from
django_admin_smoke_tests.tests.ModelAdminCheckException: Above exception occured while running test 'test_queryset' on modeladmin data_browser.ViewAdmin (View)
```

**Comment by tolomea** [comment]
Sooo
The Data Browser comes with some helpers, the main one is the AdminMixin, and it's main thing is a nicer way of dealing with annotated fields in admins.
In doing that it needs to know if it's a list request or a detail request and it figures that out by inspecting the request.
That AdminMixin is mixed into the Data Browsers own saved view admin.
This test is testing the the Data Browsers saved view admin, and it's passing a request from a request factory.
That request factory request object is not sufficiently complete to support the inspection the data browser is doing, so Boom.

If you are not otherwise using that AdminMixin then the short term fix for you is to make use Admin Smoke Tests exclude_apps setting to exclude the Data Browser.

For my part I don't like that just adding the mixin to an admin will break any test that passes a request factory request into that admin and I think I can fix it fairly easily.

**Comment by jayvdb** [comment]
Thanks for fixing this.

I was previously using `exclude_apps` to ignore this, and didnt consider it important while there were other more interesting issues.

Now I can remove that, and report any times it breaks again, and you can consider any future reports about this as very low priority as I dont need a fix.

The reason I run these smoke tests is to detect problems when upgrading py, dj, drf, etc - obscure problems arise that are not covered by the apps test suites.  And it also means that the request factory gets a good work out, so I know I can use it any time I need to write a custom test involving a model that I didn't create.

**Comment by tolomea** [comment]
No worries, the request factory thing wasn't good, that could break a lot of people admin tests. That package is interesting, I will have to remember it.

**Comment by jayvdb** [comment]
The four I use are
```
django-smoke-tests = {git = "https://github.com/jayvdb/django-smoke-tests", rev = "drf"}
django-admin-smoke-tests = {git = "https://github.com/jayvdb/django-admin-smoke-tests", rev = "all"}
django-admin-auto-tests = {git = "https://github.com/jayvdb/django-admin-auto-tests", rev = "sdist"}
schemathesis = "^2.3.1"
```

django-smoke-tests hits all endpoints with garbage.
schemathesis hits openapi drf endpoints.

Of the two admin ones, the latter is the best, but requires creating test modules with some boilerplate classes, and it cuts deeper, so I only use it for major apps (djstripe/oscar/etc) where business logic directly interacts with their app.
