### ISSUE TITLE
Compatibility with qsessions

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#17]
Recent versions of https://github.com/QueraTeam/django-qsessions causes a failure.

It seems a common class of possible problems.

https://github.com/QueraTeam/django-qsessions/commit/120ba23f4b995e3234170c7df28c99c296e59b1d

It would be great if orm_admin.py `get_models` skipped models it can not load.

```py
Traceback (most recent call last):
  File "/home/python3.8/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return self.application(environ, start_response)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/python3.8/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/python3.8/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/python3.8/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/python3.8/lib/python3.8/site-packages/data_browser/views.py", line 116, in query_html
    config = _get_config(request)
  File "/home/python3.8/lib/python3.8/site-packages/data_browser/views.py", line 77, in _get_config
    orm_models = get_models(request)
  File "/home/python3.8/lib/python3.8/site-packages/data_browser/orm_admin.py", line 323, in get_models
    _get_fields_for_model(request, model, model_admins[model], admin_fields)
  File "/home/python3.8/lib/python3.8/site-packages/data_browser/orm_admin.py", line 289, in _get_fields_for_model
    orm_field = _get_calculated_field(
  File "/home/python3.8/lib/python3.8/site-packages/data_browser/orm_admin.py", line 165, in _get_calculated_field
    field_func = getattr(admin, field_name, None)
TypeError: getattr(): attribute name must be string
```

**Comment by tolomea** [comment]
So you have something in list_display, fields or fieldsets which isn't a string? For my context I don't suppose you know what it is and where?

**Comment by tolomea** [comment]
oh, I missed the commit link, thanks for that, I always forget that callables in list_display is even a thing, I wonder if I can support those the same way I support functions on the admin class

**Comment by tolomea** [comment]
I've fixed support for callables in list_display, that will be in the next release. However the JS won't trust the HTML so the link they are inserting will not actually render as a link. If that's a problem you might want to use `ddb_hide_fields` to hide that field.

**Comment by tolomea** [comment]
As always thanks for the report.

**Comment by jayvdb** [comment]
Sounds looks an appropriate approach.  Thanks for fixing.

**Comment by tolomea** [comment]
I fixed the HTML thing as well and in the process found a nice little bit of refactoring.
