### ISSUE TITLE
Breaks on django-attachments

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#2]
https://pypi.org/project/django-attachments/

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 145, in query_html
    ctx = _get_context(request, model_name, fields)
  File "/usr/lib/python3.8/site-packages/data_browser/views.py", line 126, in _get_context
    orm_models = get_models(request)
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 165, in get_models
    model_admins, admin_fields = _get_all_admin_fields(request)
  File "/usr/lib/python3.8/site-packages/data_browser/orm.py", line 109, in _get_all_admin_fields
    _get_foreign_key(model, inline.model, inline.fk_name).name
  File "/usr/lib/python3.8/site-packages/django/forms/models.py", line 1027, in _get_foreign_key
    raise ValueError(
ValueError: 'attachments.Attachment' has no ForeignKey to 'foo.Bar'.
```

**Comment by tolomea** [comment]
Do you have any idea what "foo.Bar" refers to here?

**Comment by jayvdb** [comment]
foo.Bar can be anything.  Please see https://pypi.org/project/django-attachments

**Comment by tolomea** [comment]
I've pushed version 1.1.4 which should prevent the exception.

This is caused by GenericInlineModelAdmin instances not supporting the normal inline `fk_field`. For now I've changed it to ignore GenericInlineModelAdmin's until I can come back and look at this properly.

**Comment by tolomea** [comment]
Please let me know if that has resolved the issue.

**Comment by jayvdb** [comment]
Perfect, thanks.
