### ISSUE TITLE
Compatibility with Django Q?

### ISSUE THREAD

**Issue by djch** [tolomea/django-data-browser#47]
Hello. I went to kick the tyres of data-browser — looks awesome, thanks for sharing — but ran into an error related to [Django Q's](https://github.com/Koed00/django-q) admin.py:

```
Traceback (most recent call last):
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/views.py", line 199, in query_html
    config = _get_config(request)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/views.py", line 113, in _get_config
    orm_models = get_models(request)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/orm_admin.py", line 424, in get_models
    model_admins, admin_fields = _get_all_admin_fields(request)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/orm_admin.py", line 185, in _get_all_admin_fields
    get_common(model_admin, model)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/orm_admin.py", line 175, in get_common
    all_model_fields[model].update(from_fieldsets(admin, include_calculated=False))
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/data_browser/orm_admin.py", line 149, in from_fieldsets
    fields = admin.get_fieldsets(request, obj)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/contrib/admin/options.py", line 337, in get_fieldsets
    return [(None, {'fields': self.get_fields(request, obj)})]
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/contrib/admin/options.py", line 328, in get_fields
    form = self._get_form_for_get_fields(request, obj)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/contrib/admin/options.py", line 667, in _get_form_for_get_fields
    return self.get_form(request, obj, fields=None)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django/contrib/admin/options.py", line 680, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "/ifs-WfM5IAGo/lib/python3.7/site-packages/django_q/admin.py", line 30, in get_readonly_fields
    return list(self.readonly_fields) + [field.name for field in obj._meta.fields]

Exception Type: AttributeError at /data-browser/
Exception Value: 'NoneType' object has no attribute '_meta'
```

**Comment by djch** [comment]
Got it — thanks for the advice 👍

**Comment by tolomea** [comment]
> Maybe I should expose that in settings as a handy way of dealing with issues in third party libs.

I just released that

**Comment by djch** [comment]
Awesome! We'll remove our workaround and use that.

Already proving to be a very handy package, by the way. Particularly on a project where we (the developers) are not afforded direct access to the production environments with access to a shell etc.

**Comment by tolomea** [comment]
I'm glad it's working out for you.

It has also become a critical tool at my work. 

There's so much more I'd like to do with it, graphs, formulas, etc but unfortunately work takes up most of my headspace.

If you have any requests or issues please do reach out.

Also since you are a developer there are a couple of advanced features not covered in README.rst you might want to know about

1: Take a look at the table in the URL Format section of CONTRIBUTING.rst

2: Drop this into settings.py to enable traversal of "to many" links
```
def DATA_BROWSER_GET_FEATURE_FLAG(flag, request):
    return flag == "to_many"
```
This is behind a flag as you need a decent mental model of what it's doing to get correct results. I plan to add some explanatory tooltips and then make it generally available.

3: There is a lot in the readme I would strongly recommend giving it at least a top to bottom skim.
